feat: added display cards
DominicGBauer/information-access pull request #46
Opened 2021-09-22 22:30 UTC by RationalRyan11

# Pull Request

## Scope
Created display cards and implemented with current database setup.
https://dev.azure.com/JHNMAT015/ECO5037S%20Front%20end/_backlogs/backlog/ECO5037S%20Front%20end%20Team/Backlog%20items/?workitem=112

## Work Done
1) Created "ResultCard" component.
2) Integrated with storage branch update-articles-pyscript as of 21/09/2021.

## Steps to Test
1) Ensure information storage requirements as referenced above. 
2) ```npm run start```
3) Navigate to the "Search Results" page. 

## Screenshot
![image](https://user-images.githubusercontent.com/80746660/134430290-5f335af2-c0e7-48a1-8a6d-a6a5046775ce.png)

2021-09-23 11:56 UTC, sjwu1235 requested changes

2021-09-27 05:45 UTC, RationalRyan11 commented on src/views/SearchResults/SearchResults.vue
>    padding: 1rem 5%;
Thanks, has been removed

2021-09-27 06:53 UTC, Matt970204 submitted a review, later dismissed

2021-09-27 07:52 UTC, Matt970204 approved these changes

2021-09-27 07:53 UTC, Matt970204 approved these changes

2021-09-27 07:53 UTC, Matt970204 approved these changes

2021-09-27 07:55 UTC, sjwu1235 approved these changes

2021-09-27 07:56 UTC, merged